services:
  redpanda:
    image: docker.io/redpandadata/redpanda:latest
    container_name: redpanda-1
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      # note: kafka-addr is for internal docker network communication
      # note: advertise-kafka-addr is for communication from outside the container
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health"]
      interval: 5s
      timeout: 3s
      retries: 5

  producer:
    build: . # assuming Dockerfile is in the same directory
    container_name: producer-1
    depends_on:
      redpanda:
        condition: service_healthy
    environment:
      - KAFKA_SERVER=redpanda:29092
      - PYTHONUNBUFFERED=1
    command: python producer.py

  processor:
    build: .
    container_name: processor-1
    depends_on:
      redpanda:
        condition: service_healthy
    environment:
      - KAFKA_SERVER=redpanda:29092
      - PYTHONUNBUFFERED=1
      - WINDOW_LENGTH_SECONDS=10
    command: python -m bytewax.run processor:flow
    